# Generated by Django 3.1.3 on 2020-11-11 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='todoImage', to='todos.todo')),
            ],
        ),
    ]
